# Garden Module for nginx-ingress Controller
# Deploys ingress-nginx Helm chart with Kind-compatible configuration

kind: Deploy
type: helm
name: ingress-nginx
description: Deploy nginx ingress controller for routing external traffic

# No dependencies - cluster is managed by Makefile

spec:
  chart:
    name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: "4.14.0"
  namespace: ingress-nginx
  releaseName: ingress-nginx
  valueFiles:
    - values.yaml
  timeout: 300
  atomic: true

---
# Validation task: Wait for ingress controller to be ready
kind: Run
type: exec
name: validate-ingress-ready
description: Wait for ingress controller deployment to be ready (fail-fast)

dependencies:
  - deploy.ingress-nginx

spec:
  command:
    - bash
    - -c
    - |
      set -euo pipefail
      KUBECTL="${local.projectPath}/.tools/bin/kubectl"
      export KUBECONFIG="${local.projectPath}/.kube/config"

      echo "⏳ Waiting for ingress controller..."
      $KUBECTL rollout status deployment/ingress-nginx-controller -n ingress-nginx --timeout=120s
      echo "✅ Ingress controller ready"
